<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PG017YF7BLR" name="in.licious.test.RestAssured" tests="1" failures="0" timestamp="08 Aug 2018 13:30:10 GMT" time="1.524" errors="1">
  <testcase name="getTest" time="1.524" classname="in.licious.test.RestAssured">
    <error type="java.io.IOException" message="Server returned HTTP response code: 400 for URL: http://52.66.9.219:9200/_sql?sql=select sum(revenue),sum(quantity) from aggregation-data where date IN(&#039;2018-07-23&#039;, &#039;2018-07-16&#039;, &#039;2018-07-09&#039;, &#039;2018-07-02&#039;) and product_id =&#039;pr_5746a7a8198ef&#039; and hub_id = 4">
      <![CDATA[java.io.IOException: Server returned HTTP response code: 400 for URL: http://52.66.9.219:9200/_sql?sql=select sum(revenue),sum(quantity) from aggregation-data where date IN('2018-07-23', '2018-07-16', '2018-07-09', '2018-07-02') and product_id ='pr_5746a7a8198ef' and hub_id = 4
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.URLConnection.getContent(Unknown Source)
	at in.licious.test.RestAssured.getTest(RestAssured.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- getTest -->
</testsuite> <!-- in.licious.test.RestAssured -->
